In [10]:
from __future__ import print_function
import torch

In [4]:
import torchvision

In [7]:
import numpy as np
n = np.random.rand(5, 3)
print(n.ndim)
print(n.size)
print(n.shape)

2
15
(5, 3)


In [9]:
t = torch.rand(5, 3)
print(t.dim())
print(t.numel())
print(t.shape)
print(t.size())

2
15
torch.Size([5, 3])
torch.Size([5, 3])


In [11]:
x = torch.empty(5, 3)
print(x)

tensor([[9.2755e-39, 1.0561e-38, 4.5001e-39],
        [4.9592e-39, 4.6837e-39, 4.2246e-39],
        [1.0286e-38, 1.0653e-38, 1.0194e-38],
        [8.4490e-39, 1.0469e-38, 9.3674e-39],
        [9.9184e-39, 8.7245e-39, 9.2755e-39]])


In [12]:
x = torch.rand(5, 3)
print(x)

tensor([[0.3122, 0.4472, 0.8700],
        [0.3974, 0.8749, 0.7709],
        [0.3819, 0.1984, 0.9646],
        [0.1817, 0.5113, 0.4860],
        [0.7087, 0.1085, 0.9789]])


In [13]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [14]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [15]:
x = x.new_ones(5, 3, dtype=torch.double)      
# new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)    
# override dtype!
print(x)                                      
# result has the same size

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-0.9749,  0.5240,  1.1641],
        [-1.7957,  0.5965,  0.4642],
        [ 0.1332, -1.4631,  0.2922],
        [-0.7217,  0.1947, -0.2317],
        [-1.9724,  0.9394,  0.6746]])


In [16]:
print(x.size())

torch.Size([5, 3])


#### 加法方式1

In [17]:
y = torch.rand(5, 3)
print(x + y)

tensor([[-0.8309,  0.9378,  1.5743],
        [-1.3390,  1.3155,  0.8221],
        [ 0.1788, -0.5582,  0.3832],
        [-0.5326,  0.6137,  0.3553],
        [-1.2853,  1.6305,  1.0000]])


#### 加法方式2

In [18]:
print(torch.add(x,y))

tensor([[-0.8309,  0.9378,  1.5743],
        [-1.3390,  1.3155,  0.8221],
        [ 0.1788, -0.5582,  0.3832],
        [-0.5326,  0.6137,  0.3553],
        [-1.2853,  1.6305,  1.0000]])


#### 加法：提供一个输出 tensor 作为参数

In [19]:
result=torch.empty(5,3)
torch.add(x,y,out=result)
print(result)

tensor([[-0.8309,  0.9378,  1.5743],
        [-1.3390,  1.3155,  0.8221],
        [ 0.1788, -0.5582,  0.3832],
        [-0.5326,  0.6137,  0.3553],
        [-1.2853,  1.6305,  1.0000]])


#### 加法：in-place

In [21]:
## adds x to y
y.add_(x)
print(y)

tensor([[-0.8309,  0.9378,  1.5743],
        [-1.3390,  1.3155,  0.8221],
        [ 0.1788, -0.5582,  0.3832],
        [-0.5326,  0.6137,  0.3553],
        [-1.2853,  1.6305,  1.0000]])


### Note 注意
任何使张量会发生变化的操作都有一个前缀 ‘_’。例如：x.copy_(y), x.t_(), 将会改变 x.

In [22]:
print(x[:, 1])

tensor([ 0.5240,  0.5965, -1.4631,  0.1947,  0.9394])


In [25]:
x=torch.randn(4,4)
y=x.view(16)
z=x.view(-1,8) # the size  -1 is inferred from other dimensions
print(x.size(),y.size(),z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [26]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([-0.7514])
-0.7514173984527588


## 手写数字书别

In [1]:
# -*- coding: utf-8 -*-
import torch
import torchvision
from torchvision import datasets, transforms
# 1. 加载MNIST手写数字数据集数据和标签
transform = transforms.Compose(
    [transforms.ToTensor(),
     transforms.Normalize((0.5, ), (0.5, ))])
trainset = datasets.MNIST(root='./data', train=True,
                            download=True, transform=transform)
trainsetloader = torch.utils.data.DataLoader(trainset, batch_size=20000, shuffle=True)

testset = datasets.MNIST(root='./data', train=True,
                            download=True, transform=transform)
testsetloader = torch.utils.data.DataLoader(testset, batch_size=20000, shuffle=True)

#######如果你不放心数据有没有加载出可以将图片显示出来看下#######
# dataiter = iter(trainsetloader)
# images, labels = dataiter.next()
# import numpy as np
# import matplotlib.pyplot as plt
# plt.imshow(images[0].numpy().squeeze())
# plt.show()
# print(images.shape)
# print(labels.shape)
##########上面这段是显示图片的代码#############


# 2. 设计网络结构
first_in, first_out, second_out = 28*28,  128, 10
model = torch.nn.Sequential(
    torch.nn.Linear(first_in, first_out),
    torch.nn.ReLU(),
    torch.nn.Linear(first_out, second_out),
)

# 3. 设计损失函数
loss_fn = torch.nn.CrossEntropyLoss()

# 4. 设置用于自动调节神经网络参数的优化器
learning_rate = 1e-4
optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)

# 5. 训练神经网络（重复训练10次）
for t in range(10):
    for i, one_batch in enumerate(trainsetloader,0):
        data,label = one_batch
        data[0].view(1,784)# 将28x28的图片变成784的向量
        data = data.view(data.shape[0],-1)

        # 让神经网络根据现有的参数，根据当前的输入计算一个输出
        model_output = model(data)
        # 5.1 用所设计算损失(误差)函数计算误差
        loss = loss_fn(model_output , label)
        if i%500 == 0:
            print(loss)
        # 5.2 每次训练前清零之前计算的梯度(导数)
        optimizer.zero_grad()
        # 5.3 根据误差反向传播计算误差对各个权重的导数
        loss.backward()
        # 5.4 根据优化器里面的算法自动调整神经网络权重
        optimizer.step()

# 保存下训练好的模型,省得下次再重新训练
torch.save(model,'./my_handwrite_recognize_model.pt')
    

##########现在你已经训练好了#################
# 6. 用这个神经网络解决你的问题，比如手写数字识别，输入一个图片矩阵，然后模型返回一个数字
testdataiter = iter(testsetloader)
testimages, testlabels = testdataiter.next()

img_vector = testimages[0].squeeze().view(1,-1)
# 模型返回的是一个1x10的矩阵，第几个元素值最大那就是表示模型认为当前图片是数字几
result_digit = model(img_vector)
print("该手写数字图片识别结果为：", result_digit.max(1)[1],"标签为：",testlabels[0])

 24%|████████████████▌                                                     | 2342912/9912422 [12:55<29:20, 4299.36it/s]

KeyboardInterrupt: 